/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_home (void);
GtkWidget* create_window_admin (void);
GtkWidget* create_window_admin_add_user (void);
GtkWidget* create_dialog_addusr (void);
GtkWidget* create_window_kine (void);
GtkWidget* create_window_kine_patients (void);
GtkWidget* create_dialog_kine_add_patient (void);
GtkWidget* create_window_nutri (void);
GtkWidget* create_window_nutri_msg (void);
GtkWidget* create_window_kine_rdv (void);
GtkWidget* create_dialog_kine_add_rdv (void);
GtkWidget* create_window_admin_mod_user (void);
GtkWidget* create_window_admin_del_user (void);
GtkWidget* create_window_admin_login (void);
GtkWidget* create_window_admin_login_show (void);
GtkWidget* create_window_admin_login_edit (void);
GtkWidget* create_window_nutri_fiche (void);
GtkWidget* create_window_nutri_fiche_add (void);
GtkWidget* create_dialog_home_mdp (void);
